React homework1
grechintanya/EPAM-React-project pull request #1
Opened 2023-03-21 09:36 UTC by grechintanya

2023-03-21 14:49 UTC, KitTheProgrammer requested changes
I checked your app and here is what I found:
1. You can add new authors with empty names
2. You can't cancel the new course creation

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +	});
1. `return` statement is redundant here
2. It is better to use a function here like this: `const renderCourseList = () => <CourseCard/>`

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +	});
It is a bad idea to do it like this. Just create separate useState for each value

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +			});
`return` statement is redundant here

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +			mockedCoursesList.push(newCourse);
Mutating global variables like this is bad and can cause unexpected behavior. Create a copy of the course list in an `useState` in this component or its parent. Like this: `const [courses, setCourses] = useState([...mockedCoursesList])`

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +			console.log(mockedCoursesList);
Don't forget to remove debugging code before committing/pushing

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +					<header>
Did you mean `newCourseForm && (...`?

If `newCourseForm` is `true` it will display nothing.

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +					<header>
I think I understood what you were trying to do.
You want to hide the courses when you are creating a new one. (there is no such requirement in the homework description tho)

But, there is a better way to do it, just use the ternar operator:
`newCourseForm ? <show list> : <show form>`

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +			)}
Highlighting this part as it is a part of my previous comment

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +			setNewCourseForm((prev) => !prev);
you can do it like this: `setNewCourseForm(!newCourseForm)`

P.S.
This approach is just not necessary here you don't have any async code

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +							handleClick={() => setNewCourseForm((prev) => !prev)}
`setNewCourseForm(!newCourseForm)`

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/CreateCourse/CreateCourse.jsx
> +	});
Do it as a render function (I think I described similar issue somewhere higher)

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/CreateCourse/CreateCourse.jsx
> +		return (
`return` statement is redundant here

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/CreateCourse/CreateCourse.jsx
> +							...courseData,
Move this handler to it's own function

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/CreateCourse/CreateCourse.jsx
> +						]);
You have no need to use prev value here. just use `authors`

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/CreateCourse/CreateCourse.jsx
> +						]);
Use a render function for this purpose (I think I already provided an example for similar case somewhere earlier)

2023-03-21 14:49 UTC, KitTheProgrammer commented on src/components/CreateCourse/CreateCourse.jsx
> +	});
same here

2023-03-22 14:01 UTC, grechintanya commented on src/components/Courses/Courses.jsx
> +			});
Я не дуже зрозуміла, що тут потрібно змінити. Прибрати return?
Без нього фільтр не хоче працювати, а еслінт свариться і кажу, що у колбек-функції має бути return statment

2023-03-22 15:09 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +			});
```
const courses = mockedCoursesList.filter((course) => 
      course.title.toLowerCase().includes(query.toLowerCase()) ||
      course.id.toLowerCase().includes(query.toLowerCase()));
```

2023-03-22 15:21 UTC, KitTheProgrammer approved these changes
Well done!
20

2023-03-22 16:08 UTC, merged